-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:36:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familiar` (
  `idFamiliar` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `genero` TINYINT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFamiliar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `genero` TINYINT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `fecha_nascimiento` DATE NOT NULL,
  `Familiar_idFamiliar` INT NOT NULL,
  PRIMARY KEY (`idPaciente`, `Familiar_idFamiliar`),
  INDEX `fk_Paciente_Familiar1_idx` (`Familiar_idFamiliar` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Familiar1`
    FOREIGN KEY (`Familiar_idFamiliar`)
    REFERENCES `mydb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal_Salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal_Salud` (
  `idPersonal_Salud` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonal_Salud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `Familiar_idFamiliar` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Personal_Salud_idPersonal_Salud` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Familiar1_idx` (`Familiar_idFamiliar` ASC) VISIBLE,
  INDEX `fk_Login_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Login_Personal_Salud1_idx` (`Personal_Salud_idPersonal_Salud` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Familiar1`
    FOREIGN KEY (`Familiar_idFamiliar`)
    REFERENCES `mydb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_Personal_Salud1`
    FOREIGN KEY (`Personal_Salud_idPersonal_Salud`)
    REFERENCES `mydb`.`Personal_Salud` (`idPersonal_Salud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Signos_Vitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Signos_Vitales` (
  `idSignos_Vitales` INT NOT NULL,
  `oximetria` INT NOT NULL,
  `Frec_respiratoria` INT NOT NULL,
  `Frec_cardica` INT NOT NULL,
  `presion_arterial` INT NOT NULL,
  `glicemia` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Paciente_Familiar_idFamiliar` INT NOT NULL,
  `Paciente_Login_idLogin` INT NOT NULL,
  PRIMARY KEY (`idSignos_Vitales`, `Paciente_idPaciente`, `Paciente_Familiar_idFamiliar`, `Paciente_Login_idLogin`),
  INDEX `fk_Signos_Vitales_Paciente1_idx` (`Paciente_idPaciente` ASC, `Paciente_Familiar_idFamiliar` ASC, `Paciente_Login_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_Signos_Vitales_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente` , `Paciente_Familiar_idFamiliar`)
    REFERENCES `mydb`.`Paciente` (`idPaciente` , `Familiar_idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historia_Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historia_Clinica` (
  `id_HistoriaClinica` INT NOT NULL,
  `Diagnostico` VARCHAR(150) NOT NULL,
  `Sugerencias` VARCHAR(150) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Personal_Salud_idPersonal_Salud` INT NOT NULL,
  PRIMARY KEY (`id_HistoriaClinica`, `Paciente_idPaciente`, `Personal_Salud_idPersonal_Salud`),
  INDEX `fk_Historia_Clinica_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Historia_Clinica_Personal_Salud1_idx` (`Personal_Salud_idPersonal_Salud` ASC) VISIBLE,
  CONSTRAINT `fk_Historia_Clinica_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historia_Clinica_Personal_Salud1`
    FOREIGN KEY (`Personal_Salud_idPersonal_Salud`)
    REFERENCES `mydb`.`Personal_Salud` (`idPersonal_Salud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
